### ISSUE TITLE
genrb not found crashes CMake

### ISSUE THREAD

**Issue by tepperly** [julp/FindICU.cmake#4]
I've experienced this issue on Fedora Core 23 and an RHEL system.
CMake Error at /various/directories/cmake/FindICU.cmake:329 (message):
  genrb not found
Call Stack (most recent call first):
  CMakeLists.txt:11 (find_package)

make: *** No targets specified and no makefile found.  Stop.

My find_package does not say that ICU is required, so it seems undesirable for CMake to exit. Here is my line from CMakeLists.txt:
`find_package(ICU COMPONENTS i18n)`

On a Red Hat or derived system, it appears that the libicu package has the shared libraries, the libicu-devel package has the headers, and the icu package has genrb.  For my C++ project, it seems that I only need libicu-devel and libicu installed, so it would be nice if FindICU.cmake didn't fail if genrb isn't found.

Thanks!

**Comment by julp** [comment]
Thanks for the report. I'll move these checks for genrb/pkgdata ICU binaries to icu_generate_resource_bundle function, the only part which depends on and requires them.

**Comment by tepperly** [comment]
I believe your change has fixed my issue.  I am having trouble with older versions missing normalizer2.h, but I think that's a separate issue unrelated to FindICU.cmake.

**Comment by julp** [comment]
Thanks for your feedback. You're right, FindICU.cmake doesn't search or use normalizer2.h in any way. I also had linking errors with the normalization part of ICU's API as it has evolved few times (at least 49 and 4.4?): I found their old equivalents and do some conditional compilation.
